// CHECKSTYLE:OFF:FileLength
import java.util.HashMap;
import java.util.Map;

import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test suite for the StrictPalindromeTest class.
 * <p>
 * The provided test suite is correct and complete. You should not need to modify it. However, you
 * should understand it. You will need to augment or write test suites for later MPs.
 *
 * @see <a href="https://cs125.cs.illinois.edu/MP/2/">MP2 Documentation</a>
 */

public class StrictPalindromeTest {

    /** Timeout for our tests. */
    private static final int TEST_TIMEOUT = 1000;

    /** Pre-computed search results to test against. */
    private static final Map<String, Boolean> PRECOMPUTED_RESULTS = new HashMap<String, Boolean>();

    /**
     * Test searches that should return results.
     */
    @Test(timeOut = TEST_TIMEOUT)
    public void testIsStrictPalindrome() {
        for (Map.Entry<String, Boolean> precomputedResult : PRECOMPUTED_RESULTS
                .entrySet()) {

            String input = precomputedResult.getKey();
            Boolean expectedOutput = precomputedResult.getValue();
            Assert.assertEquals(new Boolean(StrictPalindrome.isStrictPalindrome(input)), expectedOutput);
        }
    }

    /**
     * Create a new StrictPalindromeTest.
     *
     * @throws FileNotFoundException the file not found exception
     */
    @SuppressWarnings({"checkstyle:linelength", "checkstyle:methodlength"})
    public StrictPalindromeTest() {
        /* BEGIN AUTOGENERATED CODE */
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("rKKr", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Uw`BlQxQC6", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("fubS$0+11+0$SGuf", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("[pxYKpMKw*", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("?D22D?", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("CkG%38QnCc", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("@JoJ@", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("M7[A@A[7M", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("a1SO#5ybby5#OS1f", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("RMOaiJi9 +", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("LYG* ^<^ *GYL", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("*OOdQt [h}h[ IQdOO*", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("R]|4|pR", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("]^/ /^]", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("KQ++FK", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("FtvDfS,nn,/fDvtF", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("WuM~0iE?waEi0~MuW", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("'?j?g?j?'", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("%J8t.N.X8J%", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(")]0-|3$HTy", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("oXQ7UA RCS", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Jr1)wrw{PbP{wrw)1rJ", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("]8XZLW?w?WLZX8]", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("NcD6>1p>II>p1>eDcN", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("JKc<FvvF<%KJ", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(">z^v^z1", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Tz?HtyqytH?zT", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("0P.cZ.?.qW", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("}]:/7dt&UkU&td7/:]}", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("AOOA", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("0UOUuJ/[${", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("yPpCv7issi7vCpPy", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("2.^_wpcBsfsBcpw_^.2", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("TtB/E[95]59[E/BtT", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("*VGd`KS0mwm0SK`dGV*", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("=k(q t>yV[Vy>t q(k=", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("P)aYhihYa)P", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("r6#>8C8s|;", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("8m*#93~9~39#*m8", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("UlbMU", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Y`m:jDDDj:m`F", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("H$fL``Tf$H", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("0||pP]BLu]", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("S*w3MjM3w*S", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("<;`c#cO;<", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(")k:}W.##.W!:k)", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("8l*l8", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("vKk&F@Q:Q@F&BKv", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("oQEGdXgoZ`ogXdGEQo", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("4dd4", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(")KdSkc/4wQ", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("tHcAsAcHt", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("GOAt>OG", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("<m+ks KZ:X", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("r+FvAG[Ns@", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("5zqqU}vxSSxv}Uqqz5", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("K ;+y>>y+; K", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("fu$IIII$uh", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("kH!Q4yWF8|", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("`Ff0<VA,FF,AV<0fF`", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Xzs ;$<sNBNs<$; ezX", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("%?VQ+&s[K6", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Yw*I+=K>AS", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("L;Zo`)@}&o", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("lkkkr", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("BO(UffU=OB", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("oKNErKo", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("JY05{cqN4Z", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Un2wORfW5WfROw2qU", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("n^4keE_L-=", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("kTs-1>FQQF>1--Tk", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("+rm0R6LIXILwR0mr+", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("USvU5>`6`>5UvSU", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(".y%2II2%y.", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Hh^zzcczz^hH", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("p}Ez;NN;zE}F", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Lf+;MTa[WrW[aTM;+/L", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("qfGrGfq", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("s=Y1=s", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("2*exxe|2", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("_!(!_", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("pz_qURoIoRUq_zp", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("]3FMKya]aF", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("EH~W$@vf9,", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("jHUcsF6xH$", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Lvxu]))|uxvL", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("CRI'GKru9y", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("*sie-,nK33hn,-eis*", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("*lf1fl*", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("[q0W3vWfz.", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("`_pJCeVSqqSVeCJp_`", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("OGSGG", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("[Wn$U=AddA=S$nW[", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("z*jj*z", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("|<0{h}}n[n}^h{0<|", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("A.^_f<1$$1<f_^.<", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("L5BXXB5z", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("(0fQQf0(", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("dSjjMd", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("e]<M'4oMWWMo4'M<]e", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("MNy*-NM", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("xrodF#C%C#Fdorx", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Wn=nW", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("LxGfNmkuMP", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("~COk,zYk*B", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Hq)+4S!qeeq!S4+)qH", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("_9jqj9_", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("heweh", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Q&M&Q", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("1C/+fKKf+/C1", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("f#g3JtMqXf", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("6=^[`PMDr)", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("`dEEd`", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("%ySfSy4", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("{)kf~~fk)8", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("E6C&`:toroH:`&C6E", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("<gT.[@*; ;*@[JTg<", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("NCM.MCP", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(".Yq,:ryd:,qY.", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("CRN#--F--#NRC", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("4f+*4E4*+f4", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("2mMSkD=;';=DkSMm2", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("%er(<QP0,l", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("EViKE9(y.y|9EKiVE", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Y,,Y", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("usIJ=:=JIsu", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("y/UJ ;3>+(", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(":)0qyqjcP8", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("aggX", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("-XPnyynPX-", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("h_U|:[Uuh.", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("CUWX]W]XWUC", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("GD?Qt;k^[]", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("]O8-<<K8ZZ8K<<-8O]", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Ds&{V.j3b!", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("x9k`zSC%,y", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("eIs(e", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("9*s8^z`yD_", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("vR]LevBmBveL]Rv", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("e:[:e", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("8~k*]|S'wH", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("[6s6[", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("s-.Aj2P2jA.-s", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("7w!>sjd<j_", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("<XMHaz7H';", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("0SMxt$tx|S0", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("w**[?CH7,Z", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("sF?soY6e6Yos?Fs", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("f`|S?@CxC@?P|`f", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("B y/3k6?4.", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("*77E", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("jUXDt=TaT&tDXUj", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("@dVc).-5-.)cVd@", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("c4|]]|4c", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("/<v&&R</", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("!qC6v@+DdD+@v6Cq!", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("eP%C%ppOC%Pe", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(")M(1- pZTZp -1(M)", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("/P,{&zz8{,P/", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("48IcT.VI+h", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Ssf@-~QZ,*", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("lPaZaPl", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("~;Ey^Pm;*V", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("$T1??aT$", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("s(|n'$'n|Ts", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("ge*LMu4I4uML*eg", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("d9WM[)::)[MW9d", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("]'i`P:FEjEF:P`i']", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("l8w>!M1{!>w8l", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("wPgo*..*ZgPw", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Y**Y", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("mZ&&Zm", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("&Bs&1IrpHHprI1#sB&", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("*wJJw*", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("#9Z~]|6%K%6|]~Z9H", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("N$4cEc4nN", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("C[=:C", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Vt_EV", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("&;}H/Y42kc", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("@f7m{5aq{}", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("%9}F_k!8u=", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("u|qq|u", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("lA88`K1zgz1K`88Al", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("$_UnnnU_$", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("LPVJ'A#..#A'JVPL", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("8qS[W}P?)3", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("S@_0@2}cKKc}2@0_@S", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("qqvevyuVIR", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("0~[LB;rdC5", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("R{_3p0E7@`@7E0p3_{R", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("[EXP<%Y9T9Y%<PXE[", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("1qA7B7A81", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Z#-^U~w5K%p5w~U^-#Z", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("%~])5)]~%", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("?<Sh[gAGN ", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("`BF<AzD<O<DzA<F8`", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("U'uu'U", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("=tQQw!NN!wQQtM", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("d$q/FctUTr", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("BYl8 vl%# ", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("#<`Xh;MtM;RX`<#", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("4Rk-j_T])D", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("ORmRO", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Qcs##ocQ", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("o,_bTIYITQ_,o", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(";Js;rFr;su;", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("UIKk)w8w)kKIx", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("%Yo*|b8l1b|*oY%", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("|:;]dVhh3u3hhV&];:|", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("I*w0-Q&%2.", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("qM<Rl-&nM7", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("U^02Om&84-", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("/Rp8@@8p{/", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("P{H%99%H{P", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("_l{{NzU=y2", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("2L_$m(BZ![", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("quv.rkEEkr.vuq", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Io=oI", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("kXVogQlo|olQgoVXk", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Y?3Y", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("82E<;;<E28", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("IiS//SiI", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("7aNr^]s]VrNa7", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("V;bI#YH2q<", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("/]N.C90;G'", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(",W;E;9,", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("O9eorhe9O", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("KiIZfZ8(z/z(8ZfZIiK", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("xNq$^%YChhCY%^$qNO", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put(">B%e%BA", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("L3t|>UO;-_", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("4Z>ujf9fju>Z4", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("<6QJ-t/&/t-JQ6<", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("J.q,2,q.J", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("WxLOV+KN)>", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("O;d0MdMed;O", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("KS;Rb!>4v ", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("Y2~@ZqM$V_VFMqZ@~2Y", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("25rzT{=Zph", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("txf<{=4;[%", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("#r // r#", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("~:=i%t$TkT$t%i=:5", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("tdCM0QAqGqAQ0MCdt", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("ewg6|DKHlf", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("FMD|A|DMF", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("NuF}qyua/b", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("ZQ@:V!V%^'", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("JSq.x`GXc}", false);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("T=XB1[/:l:/[1BX=T", true);
        StrictPalindromeTest.PRECOMPUTED_RESULTS
            .put("l.[K$Nh{{hN$K[.l", true);
        /* END AUTOGENERATED CODE */
    }
}
